workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      android:
        image: android-stable
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
